// Copyright (C) Microsoft Corporation. All rights reserved.
define("Environments/Providers/Kubernetes/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.AgeText = "Age";
    exports.NodeNameText = "Node Name";
    exports.NameText = "Name";
    exports.StatusText = "Status";
    exports.ImageText = "Image";
    exports.PodsDetailsText = "Pods";
    exports.StrategyText = "Strategy";
    exports.ReplicasCountText = "Pods #";
    exports.DeploymentsDetailsText = "Deployments";
    exports.ReplicasetsDetailsText = "Replicasets";
    exports.ServicesDetailsText = "Services";
    exports.ClusterIPText = "Cluster IP";
    exports.ExternalIPText = "External IP";
    exports.TypeText = "Type";
    exports.AppNameText = "App Name";
    exports.ReplicaSetText = "Replica set";
    exports.PackageText = "Package";
    exports.PipelineText = "Pipeline";
    exports.PodsText = "Pods";
    exports.PortText = "Port";
    exports.NamespaceHeadingText = "Namespace: {0}";
    exports.PivotServiceText = "Discover and load balancing";
    exports.PivotWorkloadsText = "Workloads";
    exports.PodAge = "Age";
    exports.PodIP = "IP";
    exports.Created = "Created";
    exports.AgoBy = " ago by {0}. Image: {1}";
});